/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Priya
 */
public class DeliverymanDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeliverymanDetailsFrame
     */
    public DeliverymanDetailsFrame() {
        initComponents();
        jdbStatus.setEnabled(false);
        jcbEdit.setSelected(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblID = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jlblIC = new javax.swing.JLabel();
        jlblTel = new javax.swing.JLabel();
        jlblAdd1 = new javax.swing.JLabel();
        jlblAdd2 = new javax.swing.JLabel();
        jlblPost = new javax.swing.JLabel();
        jlblCity = new javax.swing.JLabel();
        jlblStatus = new javax.swing.JLabel();
        jdbStatus = new javax.swing.JComboBox<String>();
        jtfID = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfID2 = new javax.swing.JTextField();
        jtfTel = new javax.swing.JTextField();
        jtfAdd1 = new javax.swing.JTextField();
        jtfAdd2 = new javax.swing.JTextField();
        jtfCity = new javax.swing.JTextField();
        jtfPost = new javax.swing.JTextField();
        jlblTitle = new javax.swing.JLabel();
        jbtAction = new javax.swing.JButton();
        jbtClear = new javax.swing.JButton();
        jbtBack = new javax.swing.JButton();
        jcbEdit = new javax.swing.JCheckBox();
        jlblPlaceHolder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblID.setText("Deliveryman ID :");
        jlblID.setName(""); // NOI18N
        jPanel1.add(jlblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 77, 95, -1));

        jlblName.setText("Name:");
        jlblName.setName(""); // NOI18N
        jPanel1.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 111, 95, -1));

        jlblIC.setText("IC No:");
        jlblIC.setName(""); // NOI18N
        jPanel1.add(jlblIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 111, 47, -1));

        jlblTel.setText("Telephone No:");
        jlblTel.setName(""); // NOI18N
        jPanel1.add(jlblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 149, 95, -1));

        jlblAdd1.setText("Address Line 1:");
        jlblAdd1.setName(""); // NOI18N
        jPanel1.add(jlblAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 187, 95, -1));

        jlblAdd2.setText("Address Line 2:");
        jlblAdd2.setName(""); // NOI18N
        jPanel1.add(jlblAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, 95, -1));

        jlblPost.setText("Postal Code :");
        jlblPost.setName(""); // NOI18N
        jPanel1.add(jlblPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 264, 95, -1));

        jlblCity.setText("City :");
        jlblCity.setName(""); // NOI18N
        jPanel1.add(jlblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 44, 20));

        jlblStatus.setText("Status :");
        jPanel1.add(jlblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 303, -1, -1));

        jdbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employed", "Retired", "Resigned", "Terminated" }));
        jdbStatus.setEnabled(false);
        jPanel1.add(jdbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 300, 122, -1));

        jtfID.setEnabled(false);
        jPanel1.add(jtfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 74, 98, -1));
        jPanel1.add(jtfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 108, 221, -1));
        jPanel1.add(jtfID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 108, 260, -1));
        jPanel1.add(jtfTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 146, 221, -1));
        jPanel1.add(jtfAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 184, 573, -1));
        jPanel1.add(jtfAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 222, 570, -1));
        jPanel1.add(jtfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 261, 250, -1));

        jtfPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPostActionPerformed(evt);
            }
        });
        jPanel1.add(jtfPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 261, 122, -1));

        jlblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblTitle.setText("Add New Delivery Man");
        jPanel1.add(jlblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 27, 661, -1));

        jbtAction.setText("Add Staff");
        jPanel1.add(jbtAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 404, -1, -1));

        jbtClear.setText("Reset Fields");
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });
        jPanel1.add(jbtClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 404, -1, -1));

        jbtBack.setText("Back To Menu");
        jPanel1.add(jbtBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 404, -1, -1));

        jcbEdit.setText("Edit?");
        jcbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEditActionPerformed(evt);
            }
        });
        jPanel1.add(jcbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 299, -1, -1));
        jPanel1.add(jlblPlaceHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 79, 19));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
        // TODO add your handling code here:
        jtfID.setText("");
        jtfName.setText("");
        jtfID2.setText("");
        jtfTel.setText("");
        jtfAdd1.setText("");
        jtfAdd2.setText("");
        jtfCity.setText("");
        jtfPost.setText("");
        
    }//GEN-LAST:event_jbtClearActionPerformed

    private void jtfPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPostActionPerformed

    private void jcbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEditActionPerformed
        // TODO add your handling code here:
       jdbStatus.setEnabled(jcbEdit.isSelected());
    }//GEN-LAST:event_jcbEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliverymanDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliverymanDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliverymanDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliverymanDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliverymanDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtAction;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtClear;
    private javax.swing.JCheckBox jcbEdit;
    private javax.swing.JComboBox<String> jdbStatus;
    private javax.swing.JLabel jlblAdd1;
    private javax.swing.JLabel jlblAdd2;
    private javax.swing.JLabel jlblCity;
    private javax.swing.JLabel jlblIC;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPlaceHolder;
    private javax.swing.JLabel jlblPost;
    private javax.swing.JLabel jlblStatus;
    private javax.swing.JLabel jlblTel;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JTextField jtfAdd1;
    private javax.swing.JTextField jtfAdd2;
    private javax.swing.JTextField jtfCity;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfID2;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfPost;
    private javax.swing.JTextField jtfTel;
    // End of variables declaration//GEN-END:variables
}
