/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import adt.*;
import entity.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.GregorianCalendar;
import javax.swing.JFrame;

/**
 *
 * @author Priya
 */
public class PendingDeliveryFrame extends javax.swing.JFrame {

    String dbURL = "jdbc:derby://localhost:1527/Fast"; 
    static CircularDoublyLinkedList<Deliveryman> dmList = new CircularDoublyLinkedList<Deliveryman>();
    Connection dbCon = null; 
    PreparedStatement stmt = null; 
    ResultSet rs = null;
    
    public PendingDeliveryFrame() {
        initComponents();
        fillBox();
    }

    public static CircularDoublyLinkedList<Deliveryman> getDmList() {
        return dmList;
    }

    public static void setDmList(CircularDoublyLinkedList<Deliveryman> dmList) {
        PendingDeliveryFrame.dmList = dmList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblDM = new javax.swing.JLabel();
        jlblTilte = new javax.swing.JLabel();
        jcbDM = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDisplay = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Pending Deliveries");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblDM.setText("Choose Delivey Man: ");
        getContentPane().add(jlblDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jlblTilte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTilte.setText("View Pending Deliveries");
        getContentPane().add(jlblTilte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jcbDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDMActionPerformed(evt);
            }
        });
        getContentPane().add(jcbDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, -1));

        jtaDisplay.setEditable(false);
        jtaDisplay.setBackground(new java.awt.Color(204, 204, 204));
        jtaDisplay.setColumns(20);
        jtaDisplay.setRows(5);
        jScrollPane1.setViewportView(jtaDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 640, 300));

        jLabel1.setText("   ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDMActionPerformed
        // TODO add your handling code here:
        
        String dm = jcbDM.getSelectedItem().toString().substring(0,5);
        try{
            
                DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                Connection conn = DriverManager.getConnection(dbURL);
                
                String queryStr="SELECT * FROM  TRANS WHERE DELIVERYSTATUS ='PENDING' AND DMID = "+dm;

                stmt = conn.prepareStatement(queryStr);
                ResultSet rs = stmt.executeQuery();
            
                
                String display = "No.\tOrder ID \tDate \tTime \tETA\n\n";
                int count = 1;
                
                while(rs.next())
                {
                   display+=count+++"\t"+rs.getInt(1)+" \t"+rs.getDate(2, new GregorianCalendar()).toLocalDate()+" \t"+rs.getTime(3)+" \t"+rs.getTime(5)+"\n";
                    
                }
                
                jtaDisplay.setText(display);
                
            }catch (Exception ex){
                System.out.println(ex.getMessage());
            }
        
        
    }//GEN-LAST:event_jcbDMActionPerformed

    private void fillBox(){
    
        try{
            
                DriverManager.registerDriver(new org.apache.derby.jdbc.ClientDriver());
                Connection conn = DriverManager.getConnection(dbURL);
                
                String queryStr="SELECT DMID, DMNAME FROM  DELIVERYMAN";

                stmt = conn.prepareStatement(queryStr);
                ResultSet rs = stmt.executeQuery();
            
                while(rs.next())
                {
                   jcbDM.addItem(rs.getString(1)+"  " +rs.getString(2));
                    
                }
                
            }catch (Exception ex){
                System.out.println(ex.getMessage());
            }     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingDeliveryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingDeliveryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingDeliveryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingDeliveryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingDeliveryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbDM;
    private javax.swing.JLabel jlblDM;
    private javax.swing.JLabel jlblTilte;
    private javax.swing.JTextArea jtaDisplay;
    // End of variables declaration//GEN-END:variables
}
